title: Honeywell Heater
description: 1500W Honeywell HCE317B oscillating heater
images:
  - /images/honeywell-heater/1.jpg
  - /images/honeywell-heater/2.jpg
  - /images/honeywell-heater/3.jpg
  - /images/honeywell-heater/4.jpg
category: Appliance
availability: Sold
order: 1003
manualUrl: https://www.honeywellstore.com/store/images/pdf/hce-300-ceramic-tower-heater-manual.pdf
