title: Tilt Deck Trailer
description: 10' 10" long by 55" wide deck. Lights work well, takes a 4 pin connector. Pulls well, takes a 2 inch ball.
images:
  - /images/tilt-deck-trailer/1.jpg
  - /images/tilt-deck-trailer/2.jpg
  - /images/tilt-deck-trailer/3.jpg
  - /images/tilt-deck-trailer/4.jpg
  - /images/tilt-deck-trailer/5.jpg
category: Trailer
availability: Available
